[package]
name = "win32job"
version = "1.0.4"
authors = ["Ohad Ravid <ohad.rv@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/crate/win32job"
homepage = "https://github.com/ohadravid/win32job-rs"
repository = "https://github.com/ohadravid/win32job-rs"
description = """
A safe API for Windows' job objects.
"""
categories = ["api-bindings", "os::windows-apis"]
keywords = ["job", "job-object", "win32"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies]
winapi = { version = "0.3", features = ["handleapi", "winbase", "psapi", "processthreadsapi", "jobapi2", "basetsd"] }
thiserror = "1.0"

[dev-dependencies]
rusty-fork = "0.3"